# Generated by Django 4.0.4 on 2022-05-23 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEspecie',
            fields=[
                ('idEspecie', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreEspecie', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='especie',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoriaespecie'),
        ),
    ]
