# Generated by Django 4.0.4 on 2022-05-27 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoriaespecie_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriaproducto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriaespecie'),
        ),
    ]
