# Generated by Django 4.0.4 on 2022-06-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('idDonante', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreD', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('donacion', models.IntegerField()),
            ],
        ),
    ]
