# Generated by Django 4.0.4 on 2022-06-05 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='donacion',
        ),
    ]
