# Generated by Django 4.0.4 on 2022-06-05 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_cliente_donacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='cliente',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
    ]
