# Generated by Django 4.0.4 on 2022-06-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacion',
            name='cliente',
        ),
        migrations.AddField(
            model_name='donacion',
            name='correoD',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='donacion',
            name='telefonoD',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='valordonacion',
            field=models.IntegerField(default=True),
        ),
    ]
