# Generated by Django 4.0.4 on 2022-06-05 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_donacion_cliente_donacion_correod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donacion',
            old_name='correoD',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='donacion',
            old_name='telefonoD',
            new_name='telefono',
        ),
    ]
