# Generated by Django 4.0.4 on 2022-06-05 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_correod_donacion_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacion',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='donacion',
            name='telefono',
        ),
        migrations.AddField(
            model_name='donacion',
            name='cliente',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='valordonacion',
            field=models.IntegerField(),
        ),
    ]
