# Generated by Django 4.0.4 on 2022-06-05 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_donacion_correo_remove_donacion_telefono_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donacion',
        ),
    ]
