# Generated by Django 4.0.4 on 2022-06-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_donacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCompleto', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=50)),
                ('Telefono', models.IntegerField()),
                ('Valor', models.IntegerField()),
            ],
        ),
    ]
