# Generated by Django 4.0.4 on 2022-06-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_donacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
