# Generated by Django 4.0.4 on 2022-06-06 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_donacion_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donacion',
            old_name='Correo',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='donacion',
            old_name='NombreCompleto',
            new_name='nombrecompleto',
        ),
        migrations.RenameField(
            model_name='donacion',
            old_name='Telefono',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='donacion',
            old_name='Valor',
            new_name='valor',
        ),
    ]
