# Generated by Django 4.0.4 on 2022-06-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_donacion_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
